packages:
  - client
  - e2e
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver


overrides:
  happy-dom: "20.8.9"
  picomatch: "4.0.4"
  undici: "7.24.1"
  "@xmldom/xmldom": "0.9.10"
  "axios>follow-redirects": "1.16.0"
  "resolve-protobuf-schema>protocol-buffers-schema": "3.6.1"

catalog:
  "@biomejs/biome": "2.2.0"
  "@types/node": "24.1.0"
  typescript: "5.9.3"