packages:
  - client
  - e2e
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver


overrides:
  picomatch: "4.0.4"
  "next>postcss": "8.5.14"

catalog:
  "@biomejs/biome": "2.2.0"
  "@types/node": "24.1.0"
  typescript: "5.9.3"